apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: unzip-and-ingest-test
build:
  artifacts:
    - image: nexus-docker-public-hosted.ossim.io/unzip-and-ingest
      jib: {}
  tagPolicy:
    sha256: {}
# deploy:
#  kubectl:
#    manifests:
#    - k8s-prod.yml

deploy:
  helm:
    releases:
      - name: unzip-and-ingest
        chartPath: chart
        valuesFiles:
          - chart/values-dev.yaml
        # This override is used to pass skaffold's rebuilt image to
        # imageName in the helm chart deployment.yaml.
        # If you want to use an existing image rather than skaffold's
        # comment this out and specify the image in the values-dev.yaml
        artifactOverrides:
          imageName: nexus-docker-public-hosted.ossim.io/unzip-and-ingest

