apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gegd-processing"
spec:
  selector:
    matchLabels:
      app: "gegd-processing"
  template:
    metadata:
      labels:
        app: "gegd-processing"
    spec:
      containers:
        - name: "gegd-processing"
          image: "nexus-docker-public-hosted.ossim.io/gegd-processing"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
          volumeMounts:
            - mountPath: /maxar-blacksky-data
              name: blacksky-data
            - mountPath: /maxar-skysat-data
              name: skysat-data
      volumes:
        - name: blacksky-data
          persistentVolumeClaim:
            claimName: gegd-processing-blacksky-data-pvc
        - name: skysat-data
          persistentVolumeClaim:
            claimName: gegd-processing-skysat-data-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gegd-processing
  labels:
    app: gegd-processing
data:
  application.yaml: |-
    app:
      post:
        url:
          prefix: 'https://omar-3pa-dev.ossim.io/omar-stager/dataManager/addRaster?filename='
          suffix: '&background=true&buildThumbnails=true&buildOverviews=true&buildHistograms=true&buildHistogramsWithR0=true&useFastHistogramStaging=false&overviewType=ossim_tiff_box&overviewCompressionType=NONE&thumbnailSize=512&thumbnailType=jpeg&thumbnailStretchType=auto-minmax'
      mounts:
        - bucket: maxar-blacksky-data
          ingestDirectory: ingest
          archiveDirectory: archive
        - bucket: maxar-skysat-data
          ingestDirectory: ingest
          archiveDirectory: archive
      parsing:
        dateKeys:
          - acquisitionDate
          - acquired
        omdKeyMapList:
          - key: mission_id
            oldKeys:
              - provider
              - sensorName
            values:
              - oldValue: gegd
                newValue: SkySat
              - oldValue: skysat
                newValue: SkySat
              - oldValue: Global-1
                newValue: BlackSky
      fileExtensions:
        - ntf
        - ntif
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gegd-camel-gegd-processing-blacksky-data-pv
spec:
  capacity:
    storage: 16G

  accessModes:
    - ReadWriteMany
  nfs:
    path: /maxar-blacksky-data
    server: 10.70.40.254
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gegd-camel-gegd-processing-skysat-data-pv
spec:
  capacity:
    storage: 16G

  accessModes:
    - ReadWriteMany
  nfs:
    path: /maxar-skysat-data
    server: 10.70.40.254
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gegd-processing-blacksky-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 16G
  volumeName: gegd-camel-gegd-processing-blacksky-data-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gegd-processing-skysat-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 16G
  volumeName: gegd-camel-gegd-processing-skysat-data-pv